"use client";

import { useEffect, useState, useCallback } from "react";
import { useParams } from "next/navigation";
import { Play, Loader2, RefreshCw, AlertTriangle } from "lucide-react";
import { useCampaignStore } from "@/lib/stores/campaign-store";
import { useJobs } from "@/lib/hooks/use-jobs";
import StrategyReview from "@/components/campaigns/StrategyReview";
import JobProgress from "@/components/shared/JobProgress";
import type { CampaignStrategy, CreativeConcept } from "@/lib/types";

export default function CampaignStrategyPage() {
  const { id } = useParams<{ id: string }>();
  const { campaign, research } = useCampaignStore();
  const { activeJobs, loadJobs } = useJobs(id);
  const [loading, setLoading] = useState(true);
  const [starting, setStarting] = useState(false);
  const [strategy, setStrategy] = useState<CampaignStrategy | null>(null);
  const [concepts, setConcepts] = useState<CreativeConcept[]>([]);

  const loadStrategy = useCallback(async () => {
    if (!id) return;
    try {
      const res = await fetch(`/api/campaigns/${id}/strategy`);
      if (res.ok) {
        const data = await res.json();
        setStrategy(data.strategies?.[0] || null);
        setConcepts(data.concepts || []);
      }
    } catch {
      // Will fall through to empty state
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    loadStrategy();
    if (id) loadJobs(id);
  }, [id, loadStrategy, loadJobs]);

  // When a strategy job completes, reload
  const strategyJobs = activeJobs.filter((j) => j.type === "strategy");
  const runningJob = strategyJobs.find(
    (j) => j.status === "pending" || j.status === "running"
  );
  const lastCompletedJob = strategyJobs.find(
    (j) => j.status === "completed"
  );

  useEffect(() => {
    if (lastCompletedJob) {
      loadStrategy();
    }
  }, [lastCompletedJob, loadStrategy]);

  const handleStartStrategy = async () => {
    if (!id) return;
    setStarting(true);
    try {
      const res = await fetch("/api/agents/strategy", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ campaign_id: id }),
      });

      if (res.ok) {
        if (id) loadJobs(id);
      } else {
        const err = await res.json();
        console.error("Failed to start strategy:", err);
      }
    } catch (err) {
      console.error("Failed to start strategy:", err);
    } finally {
      setStarting(false);
    }
  };

  const handleApproveConcept = async (conceptId: string) => {
    try {
      const res = await fetch("/api/approvals", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          campaign_id: id,
          org_id: campaign?.org_id,
          type: "concept",
          item_id: conceptId,
          item_summary: concepts.find((c) => c.id === conceptId)?.name,
          agent_reasoning: "Creative concept generated by strategy agent",
        }),
      });

      if (res.ok) {
        setConcepts((prev) =>
          prev.map((c) =>
            c.id === conceptId ? { ...c, status: "approved" as const } : c
          )
        );
      }
    } catch (err) {
      console.error("Failed to approve concept:", err);
    }
  };

  const handleRejectConcept = async (conceptId: string) => {
    setConcepts((prev) =>
      prev.map((c) =>
        c.id === conceptId ? { ...c, status: "rejected" as const } : c
      )
    );
  };

  const hasResearch = research.length > 0;

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header with actions */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold text-foreground">
            Campaign Strategy
          </h2>
          <p className="text-sm text-muted-foreground">
            AI-generated positioning, messaging framework, and creative concepts
          </p>
        </div>
        <div className="flex items-center gap-2">
          {strategy && (
            <button
              onClick={loadStrategy}
              className="flex items-center gap-2 px-3 py-2 text-sm text-muted-foreground hover:text-foreground border border-border rounded-lg hover:bg-muted/30 transition-colors"
            >
              <RefreshCw className="w-4 h-4" />
              Refresh
            </button>
          )}
          <button
            onClick={handleStartStrategy}
            disabled={starting || !!runningJob || !hasResearch}
            className="flex items-center gap-2 px-4 py-2.5 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 disabled:opacity-50 transition-colors"
          >
            {starting || runningJob ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Play className="w-4 h-4" />
            )}
            {runningJob
              ? "Generating..."
              : strategy
                ? "Re-generate Strategy"
                : "Generate Strategy"}
          </button>
        </div>
      </div>

      {/* No research warning */}
      {!hasResearch && !strategy && (
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-4 flex items-start gap-3">
          <AlertTriangle className="w-5 h-5 text-amber-500 mt-0.5 shrink-0" />
          <div>
            <p className="text-sm font-medium text-foreground">
              Research Required
            </p>
            <p className="text-xs text-muted-foreground mt-1">
              Run the Research agent first to gather market intelligence. The
              Strategy agent uses research findings to generate positioning,
              messaging, and creative concepts.
            </p>
          </div>
        </div>
      )}

      {/* Active strategy jobs */}
      {strategyJobs.length > 0 && (
        <div className="space-y-2">
          {strategyJobs
            .filter((j) => j.status !== "completed")
            .map((job) => (
              <JobProgress key={job.id} job={job} />
            ))}
        </div>
      )}

      {/* Strategy results */}
      <StrategyReview
        strategy={strategy}
        concepts={concepts}
        onApproveConcept={handleApproveConcept}
        onRejectConcept={handleRejectConcept}
      />

      {/* Brief context when no strategy yet */}
      {campaign?.brief && !strategy && !runningJob && hasResearch && (
        <div className="bg-card rounded-xl border border-border p-6">
          <h3 className="text-sm font-semibold text-foreground mb-3">
            Ready to Generate Strategy
          </h3>
          <p className="text-xs text-muted-foreground mb-4">
            {research.length} research finding(s) available. The strategy agent
            will use this data to develop positioning, messaging, and creative
            concepts.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
            {campaign.brief.brand_name && (
              <div>
                <span className="text-muted-foreground">Brand:</span>{" "}
                <span className="text-foreground">
                  {campaign.brief.brand_name}
                </span>
              </div>
            )}
            {campaign.brief.goals && (
              <div className="sm:col-span-2">
                <span className="text-muted-foreground">Goals:</span>{" "}
                <span className="text-foreground">{campaign.brief.goals}</span>
              </div>
            )}
            {campaign.brief.platforms?.length ? (
              <div className="sm:col-span-2">
                <span className="text-muted-foreground">Platforms:</span>{" "}
                <span className="text-foreground">
                  {campaign.brief.platforms.join(", ")}
                </span>
              </div>
            ) : null}
          </div>
        </div>
      )}
    </div>
  );
}
